# Generated by Django 3.1 on 2020-08-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vestuario', '0002_auto_20200825_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='kupac',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='datum',
            new_name='date_ordered',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='narudzba',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='produkt',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='kolicina',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='naziv',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cijena',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='kupac',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='narudzba',
            new_name='order',
        ),
    ]
